default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres

development:
  <<: *default
  database: nasa_development


test:
  <<: *default
  database: nasa_test


production:
  <<: *default
  database: nasa_production